<?php
/**
 * Class2MessagesApi
 * PHP version 5
 *
 * @category Class
 * @package  ChatApiWhatsApp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Chat API SDK
 *
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

namespace ChatApiWhatsApp\Api;

use GuzzleHttp\Client;
use GuzzleHttp\ClientInterface;
use GuzzleHttp\Exception\RequestException;
use GuzzleHttp\Psr7\MultipartStream;
use GuzzleHttp\Psr7\Request;
use GuzzleHttp\RequestOptions;
use ChatApiWhatsApp\ApiException;
use ChatApiWhatsApp\Configuration;
use ChatApiWhatsApp\HeaderSelector;
use ChatApiWhatsApp\ObjectSerializer;

/**
 * Class2MessagesApi Class Doc Comment
 *
 * @category Class
 * @package  ChatApiWhatsApp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */
class Class2MessagesApi
{
    /**
     * @var ClientInterface
     */
    protected $client;

    /**
     * @var Configuration
     */
    protected $config;

    /**
     * @var HeaderSelector
     */
    protected $headerSelector;

    /**
     * @var int Host index
     */
    protected $hostIndex;

    /**
     * @param ClientInterface $client
     * @param Configuration   $config
     * @param HeaderSelector  $selector
     * @param int             $host_index (Optional) host index to select the list of hosts if defined in the OpenAPI spec
     */
    public function __construct(
        ClientInterface $client = null,
        Configuration $config = null,
        HeaderSelector $selector = null,
        $host_index = 0
    ) {
        $this->client = $client ?: new Client();
        $this->config = $config ?: new Configuration();
        $this->headerSelector = $selector ?: new HeaderSelector();
        $this->hostIndex = $host_index;
    }

    /**
     * Set the host index
     *
     * @param  int Host index (required)
     */
    public function setHostIndex($host_index)
    {
        $this->hostIndex = $host_index;
    }

    /**
     * Get the host index
     *
     * @return Host index
     */
    public function getHostIndex()
    {
        return $this->hostIndex;
    }

    /**
     * @return Configuration
     */
    public function getConfig()
    {
        return $this->config;
    }

    /**
     * Operation forwardMessage
     *
     * Forwarding messages to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\ForwardMessageRequest $forwardMessageRequest forwardMessageRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ChatApiWhatsApp\Model\SendMessageStatus
     */
    public function forwardMessage($forwardMessageRequest)
    {
        list($response) = $this->forwardMessageWithHttpInfo($forwardMessageRequest);
        return $response;
    }

    /**
     * Operation forwardMessageWithHttpInfo
     *
     * Forwarding messages to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\ForwardMessageRequest $forwardMessageRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ChatApiWhatsApp\Model\SendMessageStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function forwardMessageWithHttpInfo($forwardMessageRequest)
    {
        $request = $this->forwardMessageRequest($forwardMessageRequest);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\ChatApiWhatsApp\Model\SendMessageStatus' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChatApiWhatsApp\Model\SendMessageStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChatApiWhatsApp\Model\SendMessageStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation forwardMessageAsync
     *
     * Forwarding messages to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\ForwardMessageRequest $forwardMessageRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function forwardMessageAsync($forwardMessageRequest)
    {
        return $this->forwardMessageAsyncWithHttpInfo($forwardMessageRequest)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation forwardMessageAsyncWithHttpInfo
     *
     * Forwarding messages to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\ForwardMessageRequest $forwardMessageRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function forwardMessageAsyncWithHttpInfo($forwardMessageRequest)
    {
        $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
        $request = $this->forwardMessageRequest($forwardMessageRequest);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'forwardMessage'
     *
     * @param  \ChatApiWhatsApp\Model\ForwardMessageRequest $forwardMessageRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function forwardMessageRequest($forwardMessageRequest)
    {
        // verify the required parameter 'forwardMessageRequest' is set
        if ($forwardMessageRequest === null || (is_array($forwardMessageRequest) && count($forwardMessageRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $forwardMessageRequest when calling forwardMessage'
            );
        }

        $resourcePath = '/forwardMessage';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($forwardMessageRequest)) {
            $_tempBody = $forwardMessageRequest;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/x-www-form-urlencoded', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('instanceId');
        if ($apiKey !== null) {
            $queryParams['instanceId'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('token');
        if ($apiKey !== null) {
            $queryParams['token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation getMessages
     *
     * Get a list of messages.
     *
     * @param  int $lastMessageNumber The lastMessageNumber parameter from the last response (optional)
     * @param  bool $last Displays the last 100 messages. If this parameter is passed, then lastMessageNumber is ignored. (optional, default to false)
     * @param  string $chatId Filter messages by chatId  Chat ID from the message list. Examples: 17633123456@c.us for private messages and 17680561234-1479621234@g.us for the group. (optional)
     * @param  int $limit Sets length of the message list. Default 100. With value 0 returns all messages. (optional)
     * @param  int $minTime Filter messages received after specified time. Example: 946684800. (optional)
     * @param  int $maxTime Filter messages received before specified time. Example: 946684800. (optional)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ChatApiWhatsApp\Model\Messages
     */
    public function getMessages($lastMessageNumber = null, $last = false, $chatId = null, $limit = null, $minTime = null, $maxTime = null)
    {
        list($response) = $this->getMessagesWithHttpInfo($lastMessageNumber, $last, $chatId, $limit, $minTime, $maxTime);
        return $response;
    }

    /**
     * Operation getMessagesWithHttpInfo
     *
     * Get a list of messages.
     *
     * @param  int $lastMessageNumber The lastMessageNumber parameter from the last response (optional)
     * @param  bool $last Displays the last 100 messages. If this parameter is passed, then lastMessageNumber is ignored. (optional, default to false)
     * @param  string $chatId Filter messages by chatId  Chat ID from the message list. Examples: 17633123456@c.us for private messages and 17680561234-1479621234@g.us for the group. (optional)
     * @param  int $limit Sets length of the message list. Default 100. With value 0 returns all messages. (optional)
     * @param  int $minTime Filter messages received after specified time. Example: 946684800. (optional)
     * @param  int $maxTime Filter messages received before specified time. Example: 946684800. (optional)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ChatApiWhatsApp\Model\Messages, HTTP status code, HTTP response headers (array of strings)
     */
    public function getMessagesWithHttpInfo($lastMessageNumber = null, $last = false, $chatId = null, $limit = null, $minTime = null, $maxTime = null)
    {
        $request = $this->getMessagesRequest($lastMessageNumber, $last, $chatId, $limit, $minTime, $maxTime);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\ChatApiWhatsApp\Model\Messages' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChatApiWhatsApp\Model\Messages', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ChatApiWhatsApp\Model\Messages';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChatApiWhatsApp\Model\Messages',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation getMessagesAsync
     *
     * Get a list of messages.
     *
     * @param  int $lastMessageNumber The lastMessageNumber parameter from the last response (optional)
     * @param  bool $last Displays the last 100 messages. If this parameter is passed, then lastMessageNumber is ignored. (optional, default to false)
     * @param  string $chatId Filter messages by chatId  Chat ID from the message list. Examples: 17633123456@c.us for private messages and 17680561234-1479621234@g.us for the group. (optional)
     * @param  int $limit Sets length of the message list. Default 100. With value 0 returns all messages. (optional)
     * @param  int $minTime Filter messages received after specified time. Example: 946684800. (optional)
     * @param  int $maxTime Filter messages received before specified time. Example: 946684800. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMessagesAsync($lastMessageNumber = null, $last = false, $chatId = null, $limit = null, $minTime = null, $maxTime = null)
    {
        return $this->getMessagesAsyncWithHttpInfo($lastMessageNumber, $last, $chatId, $limit, $minTime, $maxTime)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation getMessagesAsyncWithHttpInfo
     *
     * Get a list of messages.
     *
     * @param  int $lastMessageNumber The lastMessageNumber parameter from the last response (optional)
     * @param  bool $last Displays the last 100 messages. If this parameter is passed, then lastMessageNumber is ignored. (optional, default to false)
     * @param  string $chatId Filter messages by chatId  Chat ID from the message list. Examples: 17633123456@c.us for private messages and 17680561234-1479621234@g.us for the group. (optional)
     * @param  int $limit Sets length of the message list. Default 100. With value 0 returns all messages. (optional)
     * @param  int $minTime Filter messages received after specified time. Example: 946684800. (optional)
     * @param  int $maxTime Filter messages received before specified time. Example: 946684800. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function getMessagesAsyncWithHttpInfo($lastMessageNumber = null, $last = false, $chatId = null, $limit = null, $minTime = null, $maxTime = null)
    {
        $returnType = '\ChatApiWhatsApp\Model\Messages';
        $request = $this->getMessagesRequest($lastMessageNumber, $last, $chatId, $limit, $minTime, $maxTime);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'getMessages'
     *
     * @param  int $lastMessageNumber The lastMessageNumber parameter from the last response (optional)
     * @param  bool $last Displays the last 100 messages. If this parameter is passed, then lastMessageNumber is ignored. (optional, default to false)
     * @param  string $chatId Filter messages by chatId  Chat ID from the message list. Examples: 17633123456@c.us for private messages and 17680561234-1479621234@g.us for the group. (optional)
     * @param  int $limit Sets length of the message list. Default 100. With value 0 returns all messages. (optional)
     * @param  int $minTime Filter messages received after specified time. Example: 946684800. (optional)
     * @param  int $maxTime Filter messages received before specified time. Example: 946684800. (optional)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function getMessagesRequest($lastMessageNumber = null, $last = false, $chatId = null, $limit = null, $minTime = null, $maxTime = null)
    {
        if ($lastMessageNumber !== null && $lastMessageNumber < 0) {
            throw new \InvalidArgumentException('invalid value for "$lastMessageNumber" when calling Class2MessagesApi.getMessages, must be bigger than or equal to 0.');
        }


        $resourcePath = '/messages';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;

        // query params
        if ($lastMessageNumber !== null) {
            $queryParams['lastMessageNumber'] = ObjectSerializer::toQueryValue($lastMessageNumber);
        }
        // query params
        if ($last !== null) {
            $queryParams['last'] = ObjectSerializer::toQueryValue($last);
        }
        // query params
        if ($chatId !== null) {
            $queryParams['chatId'] = ObjectSerializer::toQueryValue($chatId);
        }
        // query params
        if ($limit !== null) {
            $queryParams['limit'] = ObjectSerializer::toQueryValue($limit);
        }
        // query params
        if ($minTime !== null) {
            $queryParams['min_time'] = ObjectSerializer::toQueryValue($minTime);
        }
        // query params
        if ($maxTime !== null) {
            $queryParams['max_time'] = ObjectSerializer::toQueryValue($maxTime);
        }


        // body params
        $_tempBody = null;

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                []
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('instanceId');
        if ($apiKey !== null) {
            $queryParams['instanceId'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('token');
        if ($apiKey !== null) {
            $queryParams['token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'GET',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendContact
     *
     * Sending a contact or contact list to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendContactRequest $sendContactRequest sendContactRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ChatApiWhatsApp\Model\SendMessageStatus
     */
    public function sendContact($sendContactRequest)
    {
        list($response) = $this->sendContactWithHttpInfo($sendContactRequest);
        return $response;
    }

    /**
     * Operation sendContactWithHttpInfo
     *
     * Sending a contact or contact list to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendContactRequest $sendContactRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ChatApiWhatsApp\Model\SendMessageStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendContactWithHttpInfo($sendContactRequest)
    {
        $request = $this->sendContactRequest($sendContactRequest);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\ChatApiWhatsApp\Model\SendMessageStatus' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChatApiWhatsApp\Model\SendMessageStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChatApiWhatsApp\Model\SendMessageStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendContactAsync
     *
     * Sending a contact or contact list to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendContactRequest $sendContactRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendContactAsync($sendContactRequest)
    {
        return $this->sendContactAsyncWithHttpInfo($sendContactRequest)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendContactAsyncWithHttpInfo
     *
     * Sending a contact or contact list to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendContactRequest $sendContactRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendContactAsyncWithHttpInfo($sendContactRequest)
    {
        $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
        $request = $this->sendContactRequest($sendContactRequest);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendContact'
     *
     * @param  \ChatApiWhatsApp\Model\SendContactRequest $sendContactRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sendContactRequest($sendContactRequest)
    {
        // verify the required parameter 'sendContactRequest' is set
        if ($sendContactRequest === null || (is_array($sendContactRequest) && count($sendContactRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sendContactRequest when calling sendContact'
            );
        }

        $resourcePath = '/sendContact';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($sendContactRequest)) {
            $_tempBody = $sendContactRequest;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/x-www-form-urlencoded', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('instanceId');
        if ($apiKey !== null) {
            $queryParams['instanceId'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('token');
        if ($apiKey !== null) {
            $queryParams['token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendFile
     *
     * Send a file to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendFileRequest $sendFileRequest sendFileRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ChatApiWhatsApp\Model\SendMessageStatus
     */
    public function sendFile($sendFileRequest)
    {
        list($response) = $this->sendFileWithHttpInfo($sendFileRequest);
        return $response;
    }

    /**
     * Operation sendFileWithHttpInfo
     *
     * Send a file to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendFileRequest $sendFileRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ChatApiWhatsApp\Model\SendMessageStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendFileWithHttpInfo($sendFileRequest)
    {
        $request = $this->sendFileRequest($sendFileRequest);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\ChatApiWhatsApp\Model\SendMessageStatus' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChatApiWhatsApp\Model\SendMessageStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChatApiWhatsApp\Model\SendMessageStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendFileAsync
     *
     * Send a file to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendFileRequest $sendFileRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendFileAsync($sendFileRequest)
    {
        return $this->sendFileAsyncWithHttpInfo($sendFileRequest)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendFileAsyncWithHttpInfo
     *
     * Send a file to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendFileRequest $sendFileRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendFileAsyncWithHttpInfo($sendFileRequest)
    {
        $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
        $request = $this->sendFileRequest($sendFileRequest);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendFile'
     *
     * @param  \ChatApiWhatsApp\Model\SendFileRequest $sendFileRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sendFileRequest($sendFileRequest)
    {
        // verify the required parameter 'sendFileRequest' is set
        if ($sendFileRequest === null || (is_array($sendFileRequest) && count($sendFileRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sendFileRequest when calling sendFile'
            );
        }

        $resourcePath = '/sendFile';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($sendFileRequest)) {
            $_tempBody = $sendFileRequest;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/x-www-form-urlencoded', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('instanceId');
        if ($apiKey !== null) {
            $queryParams['instanceId'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('token');
        if ($apiKey !== null) {
            $queryParams['token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendLink
     *
     * Send text with link and link's preview to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendLinkRequest $sendLinkRequest sendLinkRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ChatApiWhatsApp\Model\SendMessageStatus
     */
    public function sendLink($sendLinkRequest)
    {
        list($response) = $this->sendLinkWithHttpInfo($sendLinkRequest);
        return $response;
    }

    /**
     * Operation sendLinkWithHttpInfo
     *
     * Send text with link and link's preview to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendLinkRequest $sendLinkRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ChatApiWhatsApp\Model\SendMessageStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendLinkWithHttpInfo($sendLinkRequest)
    {
        $request = $this->sendLinkRequest($sendLinkRequest);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\ChatApiWhatsApp\Model\SendMessageStatus' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChatApiWhatsApp\Model\SendMessageStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChatApiWhatsApp\Model\SendMessageStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendLinkAsync
     *
     * Send text with link and link's preview to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendLinkRequest $sendLinkRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendLinkAsync($sendLinkRequest)
    {
        return $this->sendLinkAsyncWithHttpInfo($sendLinkRequest)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendLinkAsyncWithHttpInfo
     *
     * Send text with link and link's preview to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendLinkRequest $sendLinkRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendLinkAsyncWithHttpInfo($sendLinkRequest)
    {
        $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
        $request = $this->sendLinkRequest($sendLinkRequest);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendLink'
     *
     * @param  \ChatApiWhatsApp\Model\SendLinkRequest $sendLinkRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sendLinkRequest($sendLinkRequest)
    {
        // verify the required parameter 'sendLinkRequest' is set
        if ($sendLinkRequest === null || (is_array($sendLinkRequest) && count($sendLinkRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sendLinkRequest when calling sendLink'
            );
        }

        $resourcePath = '/sendLink';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($sendLinkRequest)) {
            $_tempBody = $sendLinkRequest;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/x-www-form-urlencoded', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('instanceId');
        if ($apiKey !== null) {
            $queryParams['instanceId'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('token');
        if ($apiKey !== null) {
            $queryParams['token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendLocation
     *
     * Sending a location to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendLocationRequest $sendLocationRequest sendLocationRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ChatApiWhatsApp\Model\SendMessageStatus
     */
    public function sendLocation($sendLocationRequest)
    {
        list($response) = $this->sendLocationWithHttpInfo($sendLocationRequest);
        return $response;
    }

    /**
     * Operation sendLocationWithHttpInfo
     *
     * Sending a location to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendLocationRequest $sendLocationRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ChatApiWhatsApp\Model\SendMessageStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendLocationWithHttpInfo($sendLocationRequest)
    {
        $request = $this->sendLocationRequest($sendLocationRequest);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\ChatApiWhatsApp\Model\SendMessageStatus' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChatApiWhatsApp\Model\SendMessageStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChatApiWhatsApp\Model\SendMessageStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendLocationAsync
     *
     * Sending a location to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendLocationRequest $sendLocationRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendLocationAsync($sendLocationRequest)
    {
        return $this->sendLocationAsyncWithHttpInfo($sendLocationRequest)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendLocationAsyncWithHttpInfo
     *
     * Sending a location to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendLocationRequest $sendLocationRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendLocationAsyncWithHttpInfo($sendLocationRequest)
    {
        $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
        $request = $this->sendLocationRequest($sendLocationRequest);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendLocation'
     *
     * @param  \ChatApiWhatsApp\Model\SendLocationRequest $sendLocationRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sendLocationRequest($sendLocationRequest)
    {
        // verify the required parameter 'sendLocationRequest' is set
        if ($sendLocationRequest === null || (is_array($sendLocationRequest) && count($sendLocationRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sendLocationRequest when calling sendLocation'
            );
        }

        $resourcePath = '/sendLocation';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($sendLocationRequest)) {
            $_tempBody = $sendLocationRequest;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/x-www-form-urlencoded', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('instanceId');
        if ($apiKey !== null) {
            $queryParams['instanceId'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('token');
        if ($apiKey !== null) {
            $queryParams['token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendMessage
     *
     * Send a message to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendMessageRequest $sendMessageRequest sendMessageRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ChatApiWhatsApp\Model\SendMessageStatus
     */
    public function sendMessage($sendMessageRequest)
    {
        list($response) = $this->sendMessageWithHttpInfo($sendMessageRequest);
        return $response;
    }

    /**
     * Operation sendMessageWithHttpInfo
     *
     * Send a message to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendMessageRequest $sendMessageRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ChatApiWhatsApp\Model\SendMessageStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendMessageWithHttpInfo($sendMessageRequest)
    {
        $request = $this->sendMessageRequest($sendMessageRequest);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\ChatApiWhatsApp\Model\SendMessageStatus' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChatApiWhatsApp\Model\SendMessageStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChatApiWhatsApp\Model\SendMessageStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendMessageAsync
     *
     * Send a message to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendMessageRequest $sendMessageRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendMessageAsync($sendMessageRequest)
    {
        return $this->sendMessageAsyncWithHttpInfo($sendMessageRequest)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendMessageAsyncWithHttpInfo
     *
     * Send a message to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendMessageRequest $sendMessageRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendMessageAsyncWithHttpInfo($sendMessageRequest)
    {
        $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
        $request = $this->sendMessageRequest($sendMessageRequest);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendMessage'
     *
     * @param  \ChatApiWhatsApp\Model\SendMessageRequest $sendMessageRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sendMessageRequest($sendMessageRequest)
    {
        // verify the required parameter 'sendMessageRequest' is set
        if ($sendMessageRequest === null || (is_array($sendMessageRequest) && count($sendMessageRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sendMessageRequest when calling sendMessage'
            );
        }

        $resourcePath = '/sendMessage';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($sendMessageRequest)) {
            $_tempBody = $sendMessageRequest;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/x-www-form-urlencoded', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('instanceId');
        if ($apiKey !== null) {
            $queryParams['instanceId'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('token');
        if ($apiKey !== null) {
            $queryParams['token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendPTT
     *
     * Send a ptt-audio to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendPTTRequest $sendPTTRequest sendPTTRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ChatApiWhatsApp\Model\SendMessageStatus
     */
    public function sendPTT($sendPTTRequest)
    {
        list($response) = $this->sendPTTWithHttpInfo($sendPTTRequest);
        return $response;
    }

    /**
     * Operation sendPTTWithHttpInfo
     *
     * Send a ptt-audio to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendPTTRequest $sendPTTRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ChatApiWhatsApp\Model\SendMessageStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendPTTWithHttpInfo($sendPTTRequest)
    {
        $request = $this->sendPTTRequest($sendPTTRequest);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\ChatApiWhatsApp\Model\SendMessageStatus' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChatApiWhatsApp\Model\SendMessageStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChatApiWhatsApp\Model\SendMessageStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendPTTAsync
     *
     * Send a ptt-audio to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendPTTRequest $sendPTTRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendPTTAsync($sendPTTRequest)
    {
        return $this->sendPTTAsyncWithHttpInfo($sendPTTRequest)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendPTTAsyncWithHttpInfo
     *
     * Send a ptt-audio to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendPTTRequest $sendPTTRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendPTTAsyncWithHttpInfo($sendPTTRequest)
    {
        $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
        $request = $this->sendPTTRequest($sendPTTRequest);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendPTT'
     *
     * @param  \ChatApiWhatsApp\Model\SendPTTRequest $sendPTTRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sendPTTRequest($sendPTTRequest)
    {
        // verify the required parameter 'sendPTTRequest' is set
        if ($sendPTTRequest === null || (is_array($sendPTTRequest) && count($sendPTTRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sendPTTRequest when calling sendPTT'
            );
        }

        $resourcePath = '/sendPTT';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($sendPTTRequest)) {
            $_tempBody = $sendPTTRequest;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/x-www-form-urlencoded', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('instanceId');
        if ($apiKey !== null) {
            $queryParams['instanceId'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('token');
        if ($apiKey !== null) {
            $queryParams['token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Operation sendVCard
     *
     * Sending a vcard to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendVCardRequest $sendVCardRequest sendVCardRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return \ChatApiWhatsApp\Model\SendMessageStatus
     */
    public function sendVCard($sendVCardRequest)
    {
        list($response) = $this->sendVCardWithHttpInfo($sendVCardRequest);
        return $response;
    }

    /**
     * Operation sendVCardWithHttpInfo
     *
     * Sending a vcard to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendVCardRequest $sendVCardRequest (required)
     *
     * @throws \ChatApiWhatsApp\ApiException on non-2xx response
     * @throws \InvalidArgumentException
     * @return array of \ChatApiWhatsApp\Model\SendMessageStatus, HTTP status code, HTTP response headers (array of strings)
     */
    public function sendVCardWithHttpInfo($sendVCardRequest)
    {
        $request = $this->sendVCardRequest($sendVCardRequest);

        try {
            $options = $this->createHttpClientOption();
            try {
                $response = $this->client->send($request, $options);
            } catch (RequestException $e) {
                throw new ApiException(
                    "[{$e->getCode()}] {$e->getMessage()}",
                    $e->getCode(),
                    $e->getResponse() ? $e->getResponse()->getHeaders() : null,
                    $e->getResponse() ? (string) $e->getResponse()->getBody() : null
                );
            }

            $statusCode = $response->getStatusCode();

            if ($statusCode < 200 || $statusCode > 299) {
                throw new ApiException(
                    sprintf(
                        '[%d] Error connecting to the API (%s)',
                        $statusCode,
                        $request->getUri()
                    ),
                    $statusCode,
                    $response->getHeaders(),
                    $response->getBody()
                );
            }

            $responseBody = $response->getBody();
            switch($statusCode) {
                case 200:
                    if ('\ChatApiWhatsApp\Model\SendMessageStatus' === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, '\ChatApiWhatsApp\Model\SendMessageStatus', []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
            }

            $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
            $responseBody = $response->getBody();
            if ($returnType === '\SplFileObject') {
                $content = $responseBody; //stream goes to serializer
            } else {
                $content = (string) $responseBody;
            }

            return [
                ObjectSerializer::deserialize($content, $returnType, []),
                $response->getStatusCode(),
                $response->getHeaders()
            ];

        } catch (ApiException $e) {
            switch ($e->getCode()) {
                case 200:
                    $data = ObjectSerializer::deserialize(
                        $e->getResponseBody(),
                        '\ChatApiWhatsApp\Model\SendMessageStatus',
                        $e->getResponseHeaders()
                    );
                    $e->setResponseObject($data);
                    break;
            }
            throw $e;
        }
    }

    /**
     * Operation sendVCardAsync
     *
     * Sending a vcard to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendVCardRequest $sendVCardRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendVCardAsync($sendVCardRequest)
    {
        return $this->sendVCardAsyncWithHttpInfo($sendVCardRequest)
            ->then(
                function ($response) {
                    return $response[0];
                }
            );
    }

    /**
     * Operation sendVCardAsyncWithHttpInfo
     *
     * Sending a vcard to a new or existing chat.
     *
     * @param  \ChatApiWhatsApp\Model\SendVCardRequest $sendVCardRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Promise\PromiseInterface
     */
    public function sendVCardAsyncWithHttpInfo($sendVCardRequest)
    {
        $returnType = '\ChatApiWhatsApp\Model\SendMessageStatus';
        $request = $this->sendVCardRequest($sendVCardRequest);

        return $this->client
            ->sendAsync($request, $this->createHttpClientOption())
            ->then(
                function ($response) use ($returnType) {
                    $responseBody = $response->getBody();
                    if ($returnType === '\SplFileObject') {
                        $content = $responseBody; //stream goes to serializer
                    } else {
                        $content = (string) $responseBody;
                    }

                    return [
                        ObjectSerializer::deserialize($content, $returnType, []),
                        $response->getStatusCode(),
                        $response->getHeaders()
                    ];
                },
                function ($exception) {
                    $response = $exception->getResponse();
                    $statusCode = $response->getStatusCode();
                    throw new ApiException(
                        sprintf(
                            '[%d] Error connecting to the API (%s)',
                            $statusCode,
                            $exception->getRequest()->getUri()
                        ),
                        $statusCode,
                        $response->getHeaders(),
                        $response->getBody()
                    );
                }
            );
    }

    /**
     * Create request for operation 'sendVCard'
     *
     * @param  \ChatApiWhatsApp\Model\SendVCardRequest $sendVCardRequest (required)
     *
     * @throws \InvalidArgumentException
     * @return \GuzzleHttp\Psr7\Request
     */
    protected function sendVCardRequest($sendVCardRequest)
    {
        // verify the required parameter 'sendVCardRequest' is set
        if ($sendVCardRequest === null || (is_array($sendVCardRequest) && count($sendVCardRequest) === 0)) {
            throw new \InvalidArgumentException(
                'Missing the required parameter $sendVCardRequest when calling sendVCard'
            );
        }

        $resourcePath = '/sendVCard';
        $formParams = [];
        $queryParams = [];
        $headerParams = [];
        $httpBody = '';
        $multipart = false;



        // body params
        $_tempBody = null;
        if (isset($sendVCardRequest)) {
            $_tempBody = $sendVCardRequest;
        }

        if ($multipart) {
            $headers = $this->headerSelector->selectHeadersForMultipart(
                ['application/json']
            );
        } else {
            $headers = $this->headerSelector->selectHeaders(
                ['application/json'],
                ['application/x-www-form-urlencoded', 'application/json']
            );
        }

        // for model (json/xml)
        if (isset($_tempBody)) {
            // $_tempBody is the method argument, if present
            if ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode(ObjectSerializer::sanitizeForSerialization($_tempBody));
            } else {
                $httpBody = $_tempBody;
            }
        } elseif (count($formParams) > 0) {
            if ($multipart) {
                $multipartContents = [];
                foreach ($formParams as $formParamName => $formParamValue) {
                    $multipartContents[] = [
                        'name' => $formParamName,
                        'contents' => $formParamValue
                    ];
                }
                // for HTTP post (form)
                $httpBody = new MultipartStream($multipartContents);

            } elseif ($headers['Content-Type'] === 'application/json') {
                $httpBody = \GuzzleHttp\json_encode($formParams);

            } else {
                // for HTTP post (form)
                $httpBody = \GuzzleHttp\Psr7\build_query($formParams);
            }
        }

        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('instanceId');
        if ($apiKey !== null) {
            $queryParams['instanceId'] = $apiKey;
        }
        // this endpoint requires API key authentication
        $apiKey = $this->config->getApiKeyWithPrefix('token');
        if ($apiKey !== null) {
            $queryParams['token'] = $apiKey;
        }

        $defaultHeaders = [];
        if ($this->config->getUserAgent()) {
            $defaultHeaders['User-Agent'] = $this->config->getUserAgent();
        }

        $headers = array_merge(
            $defaultHeaders,
            $headerParams,
            $headers
        );

        $query = \GuzzleHttp\Psr7\build_query($queryParams);
        return new Request(
            'POST',
            $this->config->getHost() . $resourcePath . ($query ? "?{$query}" : ''),
            $headers,
            $httpBody
        );
    }

    /**
     * Create http client option
     *
     * @throws \RuntimeException on file opening failure
     * @return array of http client options
     */
    protected function createHttpClientOption()
    {
        $options = [];
        if ($this->config->getDebug()) {
            $options[RequestOptions::DEBUG] = fopen($this->config->getDebugFile(), 'a');
            if (!$options[RequestOptions::DEBUG]) {
                throw new \RuntimeException('Failed to open the debug file: ' . $this->config->getDebugFile());
            }
        }

        return $options;
    }
}
