<?php
/**
 * SettingsTest
 *
 * PHP version 5
 *
 * @category Class
 * @package  ChatApiWhatsApp
 * @author   OpenAPI Generator team
 * @link     https://openapi-generator.tech
 */

/**
 * Chat API SDK
 *
 * The SDK allows you to receive and send messages through your WhatsApp account. [Sign up now](https://app.chat-api.com/)  The Chat API is based on the WhatsApp WEB protocol and excludes the ban both when using libraries from mgp25 and the like. Despite this, your account can be banned by anti-spam system WhatsApp after several clicking the \"block\" button.
 *
 * The version of the OpenAPI document: 1.0.0
 * Contact: sale@chat-api.com
 * Generated by: https://openapi-generator.tech
 * OpenAPI Generator version: 4.2.3
 */

/**
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Please update the test case below to test the model.
 */

namespace ChatApiWhatsApp;

use PHPUnit\Framework\TestCase;

/**
 * SettingsTest Class Doc Comment
 *
 * @category    Class
 * @description Settings
 * @package     ChatApiWhatsApp
 * @author      OpenAPI Generator team
 * @link        https://openapi-generator.tech
 */
class SettingsTest extends TestCase
{

    /**
     * Setup before running any test case
     */
    public static function setUpBeforeClass()
    {
    }

    /**
     * Setup before running each test case
     */
    public function setUp()
    {
    }

    /**
     * Clean up after running each test case
     */
    public function tearDown()
    {
    }

    /**
     * Clean up after running all test cases
     */
    public static function tearDownAfterClass()
    {
    }

    /**
     * Test "Settings"
     */
    public function testSettings()
    {
    }

    /**
     * Test attribute "webhookUrl"
     */
    public function testPropertyWebhookUrl()
    {
    }

    /**
     * Test attribute "ackNotificationsOn"
     */
    public function testPropertyAckNotificationsOn()
    {
    }

    /**
     * Test attribute "chatUpdateOn"
     */
    public function testPropertyChatUpdateOn()
    {
    }

    /**
     * Test attribute "videoUploadOn"
     */
    public function testPropertyVideoUploadOn()
    {
    }

    /**
     * Test attribute "proxy"
     */
    public function testPropertyProxy()
    {
    }

    /**
     * Test attribute "guaranteedHooks"
     */
    public function testPropertyGuaranteedHooks()
    {
    }

    /**
     * Test attribute "ignoreOldMessages"
     */
    public function testPropertyIgnoreOldMessages()
    {
    }

    /**
     * Test attribute "processArchive"
     */
    public function testPropertyProcessArchive()
    {
    }

    /**
     * Test attribute "instanceStatuses"
     */
    public function testPropertyInstanceStatuses()
    {
    }

    /**
     * Test attribute "webhookStatuses"
     */
    public function testPropertyWebhookStatuses()
    {
    }

    /**
     * Test attribute "statusNotificationsOn"
     */
    public function testPropertyStatusNotificationsOn()
    {
    }
}
